apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-node-deployment
  labels:
    app: pg-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-node
  template:
    metadata:
      labels:
        app: pg-node
    spec:
      containers:
        - name: pg-node
          image: spsaravanaselvan/pg-node:1.0
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: pg-node-service
spec:
  selector:
    app: pg-node
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
